// lineup action types
export const UPDATE_TOP_EIGHT_LINEUP = 'UPDATE_TOP_EIGHT_LINEUP'
export const UPDATE_TOP_FOUR_LINEUP = 'UPDATE_TOP_FOUR_LINEUP'
export const UPDATE_TOP_TWO_LINEUP = 'UPDATE_TOP_TWO_LINEUP'

// suit action types
export const UPDATE_SUIT_POINTS = 'UPDATE_SUIT_POINTS'